// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"RedisShake/cmd/redis-oms/biz"
	"RedisShake/cmd/redis-oms/server"
	"RedisShake/internal/config"
	"github.com/go-kratos/kratos/v2"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

// initApp init kratos application.
func InitApp(string2 string, service *config.Service, viperViper *viper.Viper) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer()
	watcher := biz.NewWatcher(viperViper)
	app := newApp(string2, service, grpcServer, watcher)
	return app, func() {
	}, nil
}
